[versions]
agp = "8.3.2"
targetSdk = "34"
jvmTarget = "17"
kotlin = "1.9.23"
ksp = "1.9.23-1.0.20"
kotlinxImmutable = "0.3.7"
material = "1.11.0"
androidxActivity = "1.8.2"
androidxFragment = "1.6.2"
androidxLifecycle = "2.7.0"
androidxRoom = "2.6.1"
androidxArchCore = "2.2.0"
androidXStartup = "1.1.1"
androidxCompose = "1.6.5"
androidxComposeSnapshot = "1.7.0-SNAPSHOT"
androidxComposeCompiler = "1.5.11"
androidxComposeMaterial3 = "1.3.0-alpha04"
androidxComposeConstraintLayout = "1.0.1"
androidxComposeNavigation = "2.7.7"
androidxCore = "1.12.0"
androidxHiltNavigationCompose = "1.2.0"
androidxMacroBenchmark = "1.2.3"
androidxNavigation = "2.5.0"
composeStableMarker = "1.0.3"
hilt = "2.51.1"
retrofit = "2.11.0"
okHttp = "4.12.0"
sandwich = "2.0.6"
landscapist = "2.3.3"
moshi = "1.15.1"
coroutines = "1.8.0"
profileInstaller = "1.3.1"
macroBenchmark = "1.2.3"
uiAutomator = "2.3.0"
truth = "1.4.2"
junit = "4.13.2"
turbine = "1.1.0"
robolectric = "4.12.1"
androidxTest = "1.5.0"
androidxTestJunit = "1.1.5"
androidTestRunner = "1.3.0-beta01"
kotlinxSerializationJson = "1.6.3"
espresso = "3.5.1"
mockito = "5.11.0"
mockito-kotlin = "5.2.1"
spotless = "6.21.0"
appcompat = "1.6.1"
baselineprofile = "1.2.3"

[libraries]
androidx-lifecycle = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidxLifecycle" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "androidxRoom" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "androidxRoom" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "androidxRoom" }
androidx-arch-core = { module = "androidx.arch.core:core-testing", version.ref = "androidxArchCore" }
androidx-startup = { module = "androidx.startup:startup-runtime", version.ref = "androidXStartup" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidxActivity" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "androidxComposeNavigation" }
androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation", version.ref = "androidxCompose" }
androidx-compose-foundation-layout = { group = "androidx.compose.foundation", name = "foundation-layout", version.ref = "androidxCompose" }
androidx-compose-material-iconsExtended = { group = "androidx.compose.material", name = "material-icons-extended", version.ref = "androidxCompose" }
androidx-compose-material = { group = "androidx.compose.material", name = "material", version.ref = "androidxCompose" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "androidxComposeMaterial3" }
androidx-compose-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout-compose", version.ref = "androidxComposeConstraintLayout" }
androidx-compose-runtime = { group = "androidx.compose.runtime", name = "runtime", version.ref = "androidxCompose" }
androidx-compose-animation = { group = "androidx.compose.animation", name = "animation", version.ref = "androidxComposeSnapshot" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "androidxComposeSnapshot" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "androidxCompose" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "androidxCompose" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidxCore" }
androidx-hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "androidxHiltNavigationCompose" }
androidx-lifecycle-runtimeCompose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidxLifecycle" }
androidx-lifecycle-viewModelCompose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "androidxLifecycle" }
androidx-test-core = { module = "androidx.test:core", version.ref = "androidxTest" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "androidxTestJunit" }
androidx-espresso = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }
compose-stable-marker = { group = "com.github.skydoves", name = "compose-stable-marker", version.ref = "composeStableMarker" }
landscapist-glide = { group = "com.github.skydoves", name = "landscapist-glide", version.ref = "landscapist" }
landscapist-animation = { group = "com.github.skydoves", name = "landscapist-animation", version.ref = "landscapist" }
landscapist-placeholder = { group = "com.github.skydoves", name = "landscapist-placeholder", version.ref = "landscapist" }
landscapist-palette = { group = "com.github.skydoves", name = "landscapist-palette", version.ref = "landscapist" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }
hilt-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "hilt" }
sandwich = { module = "com.github.skydoves:sandwich-retrofit", version.ref = "sandwich" }
retrofit = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
retrofit-moshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "retrofit" }
okhttp-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okHttp" }
okhttp-mockserver = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "okHttp" }
moshi = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshi" }
moshi-codegen = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "moshi" }
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
kotlinx-immutable-collection = { group = "org.jetbrains.kotlinx", name = "kotlinx-collections-immutable", version.ref = "kotlinxImmutable" }

# unit test
junit = { module = "junit:junit", version.ref = "junit" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }
mockito-kotlin  = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mockito-kotlin" }
turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
truth = { module = "com.google.truth:truth", version.ref = "truth" }
android-test-runner = { module = "com.android.support.test:runner", version.ref = "androidTestRunner" }
profileinstaller = { module = "androidx.profileinstaller:profileinstaller", version.ref = "profileInstaller" }
macrobenchmark = { module = "androidx.benchmark:benchmark-macro-junit4", version.ref = "macroBenchmark" }
uiautomator = { module = "androidx.test.uiautomator:uiautomator", version.ref = "uiAutomator" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }

# Dependencies of the included build-logic
android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
spotless-gradlePlugin = { group = "com.diffplug.spotless", name = "spotless-plugin-gradle", version.ref = "spotless" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
android-test = { id = "com.android.test", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
hilt-plugin = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
baselineprofile = { id = "androidx.baselineprofile", version.ref = "baselineprofile" }
